### PR TITLE
Fix bug in scripts/create_aws_event_relay_user.py

### PR DESCRIPTION
**Pull request by xbrianh**

### CODE REVIEW

**Comment by xbrianh** [comment]
The required information is already in the `integration` secret, so it is not required.

**Comment by hannes-ucsc** [comment]
Are you sure? The secrets look structurally different between staging and dev.

**Comment by hannes-ucsc** [comment]
`integration` and `dev`

**Comment by xbrianh** [comment]
The required key paths are `.AccessKey.AccessKeyId` and `.AccessKey.SecretAccessKey`, which are contained in both secrets. The `dev` secret has a bunch of extra key paths contained in the `create_access_key` response.

If I'm wrong smoketest will fail on integration. And every other test involving sync!

**Pull request merged**
