### PR TITLE
Pin major versions of direct depedencies and document dependency handling

### LINKED ISSUE #676: Dependency pinning doesn't work as intended
The issue becomes evident when you rebuild `requirements*.txt` without having made any changes to the corresponding `requirements*.txt.in` templates.

```
$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ touch requirements*.txt.in
$ make requirements*.txt
…
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   requirements-dev.txt
	modified:   requirements.txt

no changes added to commit (use "git add" and/or "git commit -a")
$ git --no-pager diff
```

A whole bunch of dependencies get upgraded, simply because newer versions were released.

```diff
(.venv) hannes-mbp:data-store hannes$ git --no-pager diff 
diff --git a/requirements-dev.txt b/requirements-dev.txt
index d0c891a..911264f 100644
--- a/requirements-dev.txt
+++ b/requirements-dev.txt
@@ -1,6 +1,7 @@
 # You should not edit this file directly.  Instead, you should edit requirements-dev.txt.in.
 asn1crypto==0.23.0
-awscli==1.11.166
+aws-xray-sdk==0.94
+awscli==1.12.2
 azure-common==1.1.8
 azure-nspkg==2.0.0
 azure-storage==0.36.0
@@ -11,7 +12,7 @@ cachetools==2.0.1
 certifi==2017.7.27.1
 cffi==1.11.1
 chained-aws-lambda==0.0.7
-chalice==1.0.3
+chalice==1.0.4
 chardet==3.0.4
 click==6.7
 clickclick==1.2.2
@@ -19,16 +20,16 @@ cloud-blobstore==0.0.7
 colorama==0.3.7
 connexion==1.1.15
 cookies==2.2.1
-coverage==4.4.1
+coverage==4.4.2
 crcmod==1.7
 cryptography==2.0.3
-docker==2.5.1
+docker==2.6.1
 docker-pycreds==0.2.1
 docutils==0.14
 domovoi==1.4.2
 elasticsearch==5.4.0
 elasticsearch-dsl==5.3.0
-flake8==3.4.1
+flake8==3.5.0
 Flask==0.12.2
 google-auth==1.1.1
 google-cloud-core==0.27.1
@@ -42,27 +43,31 @@ iso8601==0.1.12
 itsdangerous==0.24
 Jinja2==2.9.6
 jmespath==0.9.3
+jsondiff==1.1.1
+jsonpickle==0.9.5
 jsonschema==2.6.0
 MarkupSafe==1.0
 mccabe==0.6.1
 mock==2.0.0
-moto==1.1.21
-mypy==0.530
+moto==1.1.25
+mypy==0.550
 nestedcontext==0.0.4
 pbr==3.1.1
 protobuf==3.4.0
-pyaml==17.8.0
+psutil==5.4.1
+pyaml==17.10.0
 pyasn1==0.3.7
 pyasn1-modules==0.1.4
 pycodestyle==2.3.1
 pycparser==2.18
-pyflakes==1.5.0
+pyflakes==1.6.0
 Pygments==2.2.0
 python-dateutil==2.6.1
-pytz==2017.2
+pytz==2017.3
 PyYAML==3.12
 requests==2.18.4
 requests-aws4auth==0.9
+requests-http-signature==0.0.3
 rsa==3.4.2
 s3transfer==0.1.11
 six==1.11.0
@@ -72,5 +77,6 @@ typing==3.5.3.0
 urllib3==1.22
 websocket-client==0.44.0
 Werkzeug==0.12.2
+wrapt==1.10.11
 xmltodict==0.11.0
 yq==2.3.3
diff --git a/requirements.txt b/requirements.txt
index 32d21cb..c3f0c50 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -3,39 +3,40 @@ asn1crypto==0.23.0
 azure-common==1.1.8
 azure-nspkg==2.0.0
 azure-storage==0.36.0
-boto3==1.4.7
-botocore==1.7.24
+boto3==1.4.8
+botocore==1.8.2
 cachetools==2.0.1
-certifi==2017.7.27.1
-cffi==1.11.1
-chained-aws-lambda==0.0.7
+certifi==2017.11.5
+cffi==1.11.2
+chained-aws-lambda==0.0.8
 chardet==3.0.4
 click==6.7
 clickclick==1.2.2
 cloud-blobstore==0.0.7
-connexion==1.1.15
-cryptography==2.0.3
+connexion==1.2
+cryptography==2.1.3
 docutils==0.14
-elasticsearch==5.4.0
+elasticsearch==6.0.0
 elasticsearch-dsl==5.3.0
 Flask==0.12.2
-google-auth==1.1.1
-google-cloud-core==0.27.1
-google-cloud-storage==1.4.0
-google-resumable-media==0.2.3
+google-api-core==0.1.1
+google-auth==1.2.1
+google-cloud-core==0.28.0
+google-cloud-storage==1.6.0
+google-resumable-media==0.3.1
 googleapis-common-protos==1.5.3
 idna==2.6
 inflection==0.3.1
 iso8601==0.1.12
 itsdangerous==0.24
-Jinja2==2.9.6
+Jinja2==2.10
 jmespath==0.9.3
 jsonschema==2.6.0
 MarkupSafe==1.0
 nestedcontext==0.0.4
-protobuf==3.4.0
-pyasn1==0.3.7
-pyasn1-modules==0.1.4
+protobuf==3.5.0.post1
+pyasn1==0.4.2
+pyasn1-modules==0.2.1
 pycparser==2.18
 python-dateutil==2.6.1
 PyYAML==3.12
(.venv) hannes-mbp:data-store hannes$ 

```

Suppose a developer needs to make a change to one of the `requirements*.txt.in` templates. They then run `make requirements*.txt` as instructed. The resulting `requirements*.txt` files have both **intended** changes (resulting from the change in the template) as well as **incidental** changes (resulting from just running `make requirements*.txt`). One could, of course, revert the incidental changes but they are difficult to identify. It is not immediately apparent whether a dependency was bumped simply because a newer version was released or because the change to the template required it.

This is a surefire way to break the build, or even the product.

### PR DESCRIPTION
**Pull request by hannes-ucsc**
Fixes #676

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
How's this?

For 0.x.y dependencies I allowed upgrades to < 2 because for most projects you'd want to upgrade from 0.9 to 1.0 since both tend to be compatible.

**Comment by ttung** [comment]
I think the particular use case described in #676 can be handled by two sets of Makefile rules:

One builds an entirely new environment from `requirements{,-dev}.txt.in`.  Another builds an environment from the existing `requirements{,-dev}.txt` and then applies the modified `requirements{,-dev}.txt.in`.  This will constrain the changes to the newly added modules.

**Comment by kislyuk** [comment]
@hannes-ucsc, I pushed to your branch (https://github.com/HumanCellAtlas/data-store/pull/677/commits/f2c19b3b05196a73445bbf7737b19f02077a551b) to get past the lint error introduced by bumping the flake8 lint checker package.

**Comment by hannes-ucsc** [comment]
I added #678 to capture @ttung's comment, which I think is worth exploring.

**Pull request merged**
