### PR TITLE
Update deployment environment example and other fixes

### PR DESCRIPTION
**Pull request by brainstorm**
Minor fixes for #1684, #1694, #1712, #1715, #1718.

### CODE REVIEW

**Comment by brainstorm** [comment]
I guess that CI is broken for non-org members? Guessing from the [aws configure error](https://travis-ci.com/HumanCellAtlas/data-store/jobs/161569341#L732).

**Comment by brainstorm** [comment]
Other minor changes I decided not to include on this PR but might be worth considering (since they helped me advance in my deployment efforts, so they might be helpful to third parties):

```diff
diff --git a/infra/elasticsearch/access_ips.tf b/infra/elasticsearch/access_ips.tf
deleted file mode 100644
index f0d93e5..0000000
--- a/infra/elasticsearch/access_ips.tf
+++ /dev/null
@@ -1,8 +0,0 @@
-data "aws_secretsmanager_secret_version" "source_ips" {
-  secret_id = "${var.DSS_SECRETS_STORE}/${var.DSS_DEPLOYMENT_STAGE}/${var.ES_ALLOWED_SOURCE_IP_SECRETS_NAME}"
-}
-
-locals {
-  ips_str = "${data.aws_secretsmanager_secret_version.source_ips.secret_string}"
-  access_ips = "${compact(split(",", local.ips_str))}"
-}
diff --git a/infra/elasticsearch/main.tf b/infra/elasticsearch/main.tf
index 665e907..afc07a1 100644
--- a/infra/elasticsearch/main.tf
+++ b/infra/elasticsearch/main.tf
@@ -1,5 +1,6 @@
 data aws_caller_identity current {}
 data aws_region current {}
+
 locals {
   region = "${data.aws_region.current.name}"
   account_id = "${data.aws_caller_identity.current.account_id}"
@@ -43,7 +44,7 @@ resource "aws_cloudwatch_log_resource_policy" "dss_es_cloudwatch_policy" {
   policy_document = "${data.aws_iam_policy_document.dss_es_cloudwatch_policy_document.json}"
 }

-data "aws_iam_policy_document" "dss_es_access_policy_documennt" {
+data "aws_iam_policy_document" "dss_es_access_policy_document" {
   statement {
     principals {
       type = "AWS"
@@ -63,7 +64,7 @@ data "aws_iam_policy_document" "dss_es_access_policy_documennt" {
     condition {
       test = "IpAddress"
       variable = "aws:SourceIp"
-      values = ["${local.access_ips}"]
+      values = ["${var.ES_ALLOWED_SOURCE_IP_SECRET_STRING}"]
     }
   }
 }
@@ -71,7 +72,7 @@ data "aws_iam_policy_document" "dss_es_access_policy_documennt" {
 resource aws_elasticsearch_domain elasticsearch {
   count = "${length(var.DSS_ES_DOMAIN) > 0 ? 1 : 0}"
   domain_name = "${var.DSS_ES_DOMAIN}"
-  elasticsearch_version = "5.5"
+  elasticsearch_version = "6.3"

   cluster_config = {
     instance_type = "${var.DSS_ES_INSTANCE_TYPE}"
@@ -114,5 +115,5 @@ resource aws_elasticsearch_domain elasticsearch {
     Domain = "${var.DSS_ES_DOMAIN}"
   }

-  access_policies = "${data.aws_iam_policy_document.dss_es_access_policy_documennt.json}"
+  access_policies = "${data.aws_iam_policy_document.dss_es_access_policy_document.json}"
 }
diff --git a/infra/gcp_service_account/main.tf b/infra/gcp_service_account/main.tf
index b59a961..27bfc0c 100644
--- a/infra/gcp_service_account/main.tf
+++ b/infra/gcp_service_account/main.tf
@@ -1,5 +1,10 @@
 data "google_project" "project" {}

+#resource "google_project_service" "project" {
+#  project = "${data.google_project.project.project_id}"
+#  service = "iam.googleapis.com"
+#}
+
 resource "google_service_account" "dss" {
   display_name = "${var.DSS_GCP_SERVICE_ACCOUNT_NAME}"
   account_id = "${var.DSS_GCP_SERVICE_ACCOUNT_NAME}"
diff --git a/requirements-dev.txt b/requirements-dev.txt
index 1635568..1857371 100644
--- a/requirements-dev.txt
+++ b/requirements-dev.txt
@@ -29,7 +29,7 @@ dcplib==1.4.0
 dnspython==1.15.0
 docutils==0.14
 domovoi==1.8.3
-elasticsearch==5.5.3
+elasticsearch==6.3
 elasticsearch-dsl==6.2.1
 enum-compat==0.0.2
 Faker==0.9.2
```

**Comment by Bento007** [comment]
If you could break this into smaller PR's that address each specific issues that would be appreciated. It makes it easier to review and back out if necessary.

**Comment by brainstorm** [comment]
Sure, closing.

**Pull request closed without merging**
