### PR TITLE
dependency bump: urllib1.25.3

### LINKED ISSUE #2109: Update urllib3.
Right now snyk is failing because urllib3 is not the latest version, however, upgrading to the latest version seems to enforce a machine specific SSL check that fails multiple tests:
```
======================================================================
ERROR: test_copy_part_gs_to_s3 (__main__.TestSyncUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
```
https://travis-ci.com/HumanCellAtlas/data-store/jobs/198397296

Low priority in my eyes, but posting this here until resolved.

### PR DESCRIPTION
**Pull request by amarjandu**
Bump urllib to v1.25.3 (latest)

Resolves #2109

### CODE REVIEW

**Comment by amarjandu** [comment]
**Note:** We should `make deploy` this to DEV and test with `make smoketest` prior to merging, just to ensure there is no dependency issues off the bat.

**Comment by DailyDreaming** [comment]
@amarjandu #2109 is primarily a ticket to add the cert validation to the gitlab runner so that it's compatible with the latest version of urllib3.

**Comment by amarjandu** [comment]
@DailyDreaming ah ok ill look into allspark for certificate setup; there was also a dependency bump from #2207 which was sent from one of the security bots; but the bot does not know how the `.in` files are utilized, so we still have to manually perform the bump.

**Comment by amarjandu** [comment]
@DailyDreaming I checked allspark-eks-runner for the certifications, and it would appear that the runner already has access to the certificate; however the `travis-ci.yml` does not have use a particular image that it runs, or appear to explicitly download the image from `https://dss.dev.data.humancellatlas.org`.

There could be the addiction of the certificate to travis during its setup time by:
`echo -n | openssl s_client -connect https://dss.{stage}.data.humancellatlas.org:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt`

there might need to be some changes for prod certificate due to URL changes.....

With that being said, i dont see the same error occur for travis, with this current update to 1.25.3.
it would appear that there were some changes made to the way the SSL certificates are pulled in this version which was updated after your initial Issue submission. See change log https://pypi.org/project/urllib3/#description

**Pull request merged**
