### PR TITLE
Adjusting async copy threshold to >= ASYNC_COPY_THRESHOLD

### PR DESCRIPTION
**Pull request by Bento007**
### Test plan
- Modified test cases to verify the upload of files with sizes +-1 of ASYNC_COPY_THRESHOLD.

### Release notes
- Relates to https://github.com/HumanCellAtlas/dcp-cli/issues/120

### CODE REVIEW

**Comment by ttung** [comment]
I don't get this bug.  What exactly goes wrong?

**Comment by Bento007** [comment]
@ttung Currently the DSS is unable to upload files that are size 64 * 1024 * 1024

**Comment by Bento007** [comment]
This is what is currently breaking master.

**Comment by Bento007** [comment]
It looks like the `src_metadata` does not match the `dst_metadata` when file size is 64MB.

`dst_metadata = 'c1d1c1cdcddfe4fc0a05bd0905c07d7d-1'`
`src_metadata = '9d82856db4ebb66ad77d336a2d37dbb8'`

**Comment by Bento007** [comment]
Closing in favor of #1456

**Pull request closed without merging**
