### PR TITLE
Replicating smoke test using GCP

### PR DESCRIPTION
**Pull request by Bento007**
* Moved common setup code to setUpClass
* Added support for testing additional replicas

### CODE REVIEW

**Comment by Bento007** [comment]
Connects to #1292

**Comment by ttung** [comment]
Did you try running this smoke test?

There is still s3-only code in there:

```
        # Wait for the checkout to complete and assert its success
        #
        for i in range(10):
            res = run_for_json(f"{self.venv_bin}hca dss get-bundles-checkout --checkout-job-id {checkout_job_id}")
            status = res['status']
            self.assertGreater(len(status), 0)
            if status == 'RUNNING':
                time.sleep(6)
            else:
                self.assertEqual(status, 'SUCCEEDED')
                blob_handle = S3BlobStore.from_environment()
                object_key = get_dst_bundle_prefix(bundle_uuid, bundle_version)
                print(f"Checking bucket {self.checkout_bucket} object key: {object_key}")
                files = list(blob_handle.list(self.checkout_bucket, object_key))
                self.assertEqual(len(files), file_count)
                break
        else:
            self.fail("Timed out waiting for checkout job to succeed")
```

**Comment by Bento007** [comment]
@ttung I ran the smoke test and it passed for `aws` but not for `gcp`. We need to finish adding support for `gcp` in some areas. S3 is required for this part of the test since we only support checking out to `S3`.

**Comment by ttung** [comment]
The master integration test was consistently broken. Feel free to remerge this if I'm mistaken about the cause.

**Pull request merged**
