### PR TITLE
Region env vars for some GS buckets

### PR DESCRIPTION
**Pull request by xbrianh**
Workaround for GS test buckets living in a different region than the dev bucket... for some reason.

connects to #856

### CODE REVIEW

**Comment by mweiden** [comment]
@xbrianh can you help me understand what brought this about?

**Comment by xbrianh** [comment]
@mweiden The Google `dev` bucket is not in the same region as the Google test and test-fixtures buckets. The Terraform scripts needs extra variables, beyond `GCP_DEFAULT_REGION`, to describe this. There is also a region mismatch in `staging`.

One alternative is migrating the buckets, if there's not a good reason for them to be in different regions.

**Comment by xbrianh** [comment]
@mweiden Do you want to provide any extra input before this is merged?

**Comment by mweiden** [comment]
@xbrianh no, other than you need to resolve the merge conflicts here

**Pull request merged**
