### PR TITLE
Changing dss-api lambda to use 256 memory

### PR DESCRIPTION
**Pull request by Bento007**

### CODE REVIEW

**Comment by ttung** [comment]
We should put a simple time.time() before and after the import block and feed that to analytics.

**Comment by Bento007** [comment]
@mweiden the other daemons are already set to 1536 MB. The DSS-API was the only once set bellow that.

**Comment by Bento007** [comment]
@ttung we did something to that effect, see https://github.com/HumanCellAtlas/data-store/issues/1300#issuecomment-397090068

**Comment by mweiden** [comment]
@Bento007 OK, I see. OK go ahead and 🚢

**Comment by ttung** [comment]
> @ttung we did something to that effect, see #1300 (comment)

that should be landed for every daemon so we can keep track of how performance is.
we should also track how often daemons time out.

**Comment by mweiden** [comment]
@ttung @Bento007 Just an 💡: this _could_ be accomplished by doing the xray imports first and wrapping imports with a timing subsegment.

**Comment by ttung** [comment]
How expensive is the xray import?

**Comment by ttung** [comment]
Also, I noticed the lambda logs reveal how much memory was consumed per execution.  We should aggregate P10,P50,P90 for that statistic per daemon.

**Pull request merged**
