### PR TITLE
Changed where test data is retrieved from.

### PR DESCRIPTION
**Pull request by Bento007**
Test data is now retrieved and stored in test/fixtures. This gives us more control over our test data especially as new versions of data bundles are released.

### Release notes
Changed where test data is retrieved from. Test data is now populated from test/fixtures.

### CODE REVIEW

**Comment by ttung** [comment]
If we're doing this, is there still a need for `data-bundle-examples` to be a git submodule?

**Comment by Bento007** [comment]
I don't see a reason for it.

**Comment by mikebaumann** [comment]
smoketest.py uses the `data-bundle-examples` submodule.

**Comment by Bento007** [comment]
we can leave `data-bundle-examples` for now and take it out when we're ready.

**Pull request merged**
