### PR TITLE
move get_env to tests/infra.py

### PR DESCRIPTION
**Pull request by ttung**

### CODE REVIEW

**Comment by kislyuk** [comment]
What's the difference between utils and infra? Can we document it in those files?

Also, I'm a fan of relative imports (`from .infra import foo`). They avoid possible ambiguity with namespaces and can help in refactoring. Is there a reason not to use them here?

**Comment by kislyuk** [comment]
Sorry, never mind about my question about utils vs. infra... I see you've blown away `utils.py` altogether.

**Comment by ttung** [comment]
I'll switch to relative imports in a different PR.

**Comment by ttung** [comment]
Turns out you can't do relative imports when you run a module's file as a standalone script.

**Pull request merged**
