### PR TITLE
Fixing subsegment traces in aws Lambdas

### PR DESCRIPTION
**Pull request by Bento007**
Using Xray to profile lambdas we would like to use subsegments to profile specific segments of code. Currently subsegment tracing is not working using `dss.util.tracing.begin_segment` and `dss.util.tracing.end_segment`. This PR aims to fix that.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
I would change this to not end a subsegment when an exception occurs. A subsegment should only be closed when the code inside it runs successfully. Otherwise exceptions would distort your timing stats and they won't be obviously visible as open subsegments.

**Comment by Bento007** [comment]
I agree, I'll just removed the context manager code.

**Comment by mweiden** [comment]
@Bento007 Oops, I misread the documentation on `end_segment`. Thanks for catching this.

**Comment by hannes-ucsc** [comment]
I think you should still use a CM because it provides a more concise syntax, but your `__exit__` methods needs to be a little bit smarter. That method can actually detect whether it is being called in an exception handling situation or under normal conditions.

https://www.python.org/dev/peps/pep-0343/#specification-the-with-statement

Note the parameters passed to the __exit__ method.

**Comment by Bento007** [comment]
@hannes-ucsc thanks for the info. I modified the context manager to raise if an exception is found, but the subsegments is still closed. This will allow xray to mark it as an error when profiling to prevent exceptions from polluting our timing metrics.

**Pull request merged**
