### PR TITLE
Update swagger with explicit retry-after headers.

### PR DESCRIPTION
**Pull request by DailyDreaming**
This PR explicitly adds Retry-After headers to [500, 502, 503, 504] responses for all methods except `POST /bundles/{uuid}/checkout`.

This allows the client to know which codes to retry on, even if it is a POST request (currently there is a desire to retry on POST search, see: https://github.com/HumanCellAtlas/dcp-cli/issues/222 ).

*Current CLI behavior:*
Do not retry on POST methods.  Retry on 500, 502, 503, & 504 for all non-POST methods.

*Updating the swagger would:*
Allow changes in the `dcp-cli` to retry on POST search but not `POST /bundles/{uuid}/checkout`.

### CODE REVIEW

**Comment by DailyDreaming** [comment]
@xbrianh @kislyuk Is this a better solution than https://github.com/HumanCellAtlas/dcp-cli/pull/267 ?

I'd want to follow this up with deleting this line (setting `status_forcelist=set()`): https://github.com/HumanCellAtlas/dcp-cli/blob/master/hca/util/__init__.py#L207

And changing `retry_after_status_codes={301}` to `retry_after_status_codes={301, 500, 502, 503, 504}` here: https://github.com/HumanCellAtlas/dcp-cli/blob/master/hca/util/__init__.py#L118

**Comment by DailyDreaming** [comment]
@xbrianh @kislyuk Is this a better solution than https://github.com/HumanCellAtlas/dcp-cli/pull/267 ?

I'd want to follow this up with deleting this line (setting `status_forcelist=set()`): https://github.com/HumanCellAtlas/dcp-cli/blob/master/hca/util/__init__.py#L207

And changing `retry_after_status_codes={301}` to `retry_after_status_codes={301, 500, 502, 503, 504}` here: https://github.com/HumanCellAtlas/dcp-cli/blob/master/hca/util/__init__.py#L118

**Comment by kislyuk** [comment]
This is better, but is there a way to de-duplicate these definitions so they can be defined once and referenced using `$ref` or something like that?

As a last resort, you could use a YAML anchor+reference, although I prefer not to use those.

**Comment by DailyDreaming** [comment]
@kislyuk I'll look into it, thank you.

**Comment by DailyDreaming** [comment]
@kislyuk Should be addressed.

**Comment by DailyDreaming** [comment]
@kislyuk How's this?

**Comment by DailyDreaming** [comment]
@kislyuk Changed.  Thanks for taking a look!

**Pull request merged**
