### PR TITLE
Clean up tests

### PR DESCRIPTION
**Pull request by ttung**
1. move sync tests to its own module.
2. move the code to fire up verbose logging to its own module.

### CODE REVIEW

**Comment by kislyuk** [comment]
Huh, I thought our linter was configured to a 120 col max: https://github.com/HumanCellAtlas/data-store/blob/master/.flake8#L2

Are you using a different linter?

**Comment by kislyuk** [comment]
(And as indicated in the linter config, I'm a fan of setting a 120 line max and empowering developers to make their own decisions about readability within that limit.)

**Comment by kislyuk** [comment]
This LGTM but it needs merging with my changes in https://github.com/HumanCellAtlas/data-store/pull/92, sorry :grin:

**Comment by ttung** [comment]
My editor apparently likes to flag PEP8 violations.

I'll undo the 80-col changes.

**Comment by ttung** [comment]
Let me review #92, and I'll land this after you.

**Comment by ttung** [comment]
I rebased this on top of #92, ready for review.

**Comment by ttung** [comment]
I am going to commit this based on your comment "This LGTM ..." :)

**Comment by kislyuk** [comment]
👍 
I think you'll want to rebase on top of master and re-migrate the file contents - there are a few changes to the test like the ugly hack to ignore GCSTS errors.

**Comment by ttung** [comment]
The GCSTS hack is in a `dss/events/handlers/sync.py`.  I did migrate the contents earlier though.

**Comment by kislyuk** [comment]
Oh right. Sorry, just checking.

**Pull request merged**
