### PR TITLE
Add test for bundle with multiple files of the same name

### PR DESCRIPTION
**Pull request by hannes-ucsc**
If we allow duplicate file names in a bundle—and I'm not sure we do—we should have a test for it.

Is this a good way to test it?

### CODE REVIEW

**Comment by kislyuk** [comment]
I think we should try to prevent duplicate file names. Is there a technical reason to avoid doing it?

**Comment by hannes-ucsc** [comment]
@kislyuk I'm not aware of a requirement for duplicate file names in a bundle. I suspect that most people would intuitively expect a bundle to act like a archived file system directory similar to a tarball or zip file.

**Comment by hannes-ucsc** [comment]
Note to self: create ticket before closing this.

**Comment by ttung** [comment]
Strongly advocate prohibiting multiple files with the same filename, as downloading a bundle via the cli tools will be extremely confusing otherwise.

**Comment by hannes-ucsc** [comment]
https://github.com/HumanCellAtlas/data-store/issues/1268

**Pull request closed without merging**
