### PR TITLE
Add a simple logging facility.

### PR DESCRIPTION
**Pull request by ttung**
- Logs to cloudwatch.
- Creates the group and stream, if necessary.
- Retrieves the uploadSequenceToken to log to existing streams.
- Adds test to verify most of the functionality.  The key functionality that is not tested is the creation of a logging group.  Rationale: There's a hard limit on the number of test groups.  If this test goes wild, it might do bad things to the account.

### CODE REVIEW

**Comment by ttung** [comment]
I looked at watchtower, and it's a lot more than I need.  I think the only mode that makes sense to use it in independent from python's logging module (to avoid clobbering the logging format for the entire app) and in synchronous mode (so we don't have to manage the `atexit` logic).

**Comment by kislyuk** [comment]
I have two concerns:
- What's the rationale for not using the stdlib logging module? The logging format can be adjusted on a per-logger basis.
- What's the rationale for not using threaded/asynchronous logging? I'm concerned about the synchronous RTT delays introduced by the per-message overhead.

If you don't want to plug in to the complexity of logging/threading/atexit, then maybe this will help: simply using `print()` in a lambda results in an asynchronous delivery of a cloudwatch logs message to an `/aws/lambda/<fn>` log group (that log delivery is managed by the lambda host). Is that not sufficient?

**Comment by ttung** [comment]
> What's the rationale for not using the stdlib logging module? The logging format can be adjusted on a per-logger basis.

The only thing I see for adjusting the logging format is https://docs.python.org/3/library/logging.html#logging.basicConfig, and that's a module-level method.  Is there something else?

> What's the rationale for not using threaded/asynchronous logging? I'm concerned about the synchronous RTT delays introduced by the per-message overhead.

I agree that this is not great. :(

> If you don't want to plug in to the complexity of logging/threading/atexit, then maybe this will help: simply using print() in a lambda results in an asynchronous delivery of a cloudwatch logs message to an /aws/lambda/<fn> log group (that log delivery is managed by the lambda host). Is that not sufficient?

My reluctance for using this approach is that it's pretty hard to trace.  I found a `None` getting printed for each of my lambda invocations.  It took me forever to trace it down to a print in one of the libraries we were pulling in (chalice or domovoi).  I considered doing a logging shim that just annotates the log messages so we can ignore the messages that lack the annotation and just treat those as noise.

The second reason is that approach makes it difficult to aggregate logs for a logical concept (i.e., chunked_worker or sync) that may span lambdas.

**Comment by kislyuk** [comment]
> a module-level method. Is there something else?

This is slightly messier than it would ideally be, but it works:
```
import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
logger.propagate = False
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter('DSS_LOG:%(name)s:%(pathname)s:%(lineno)s:%(levelname)s: %(message)s'))
logger.addHandler(handler)

logger.info("log log log")
```

> I considered doing a logging shim that just annotates the log messages so we can ignore the messages that lack the annotation and just treat those as noise.

I prefer that approach.

**Comment by kislyuk** [comment]
(With my example above, you get a log channel ID, logger ID, file and line number, so identifying the message should be very unambiguous. I agree it would be ideal to control the log group name as well, but I don't see a way to properly do that without threads/buffers/atexit).

**Comment by ttung** [comment]
Abandoning in favor of watchtower.

**Pull request closed without merging**
