### PR TITLE
Deploy elasticsearch with terraform

### PR DESCRIPTION
**Pull request by xbrianh**

### CODE REVIEW

**Comment by xbrianh** [comment]
Infrastructure managed by Terraform should be updated with Terraform, not with the console.

If we don't want ES access IPs to appear in the repo, Secrets Manager seems like a decent solution. The procedure to update access IPs (update the secret and run `make deploy-infra`), is more awkward than before, unfortunately.

**Comment by hannes-ucsc** [comment]
> Infrastructure managed by Terraform should be updated with Terraform, not with the console.

Can you explain why we need to be dogmatic about this? The approach I propose seems to be more practical.

> If we don't want ES access IPs to appear in the repo

I agree that we don't. Not because they are secret, but because they change all the time.

Also, let me ask again: Is there a way to tell Terraform to not touch the policy on redeployments?

**Comment by xbrianh** [comment]
If changes are made outside of Terraform, the state file becomes out-of-date.

IMO if we want to "deploy and forget", or "deploy and manage elsewhere", we should not use Terraform.

**Comment by hannes-ucsc** [comment]
> If changes are made outside of Terraform, the state file becomes out-of-date.

And why is that a problem?

Also, let me ask again: Is there a way to tell Terraform to not touch the policy on redeployments?

**Comment by hannes-ucsc** [comment]
To formulate the question differently: I'v noticed that the policy is optional in the TF module for ES. If you omit the policy from the TF config, will the state file contain a value for the policy? If it doesn't, then the state file would not become stale by users modifying the console through the console or the CLI.

From a birds eye perspective, I would be surprised if TF had this black or white approach to managed resources: either a resource is managed by TF and you can't configure any aspect of it through any other means than TF. That seems improbable but I don't know TF at all.

**Comment by mweiden** [comment]
@hannes-ucsc Just want to add a datapoint in weighing the alternatives here: to my understanding, you don't have to redeploy to change the access policy on a terraform-managed ES cluster. Doing a `terraform apply` will simply change the access policy if that is the only difference in configuration.

**Comment by xbrianh** [comment]
The ES access policy may be deployable externally to TF, but it seems unclear that a hybrid deployment is better than managing a list IPs through secrets manager.

Moving forward for now.

**Comment by xbrianh** [comment]
Connects to #856

**Pull request merged**
