### PR TITLE
Add initial set of managed wheels

### PR DESCRIPTION
**Pull request by kislyuk**

### CODE REVIEW

**Comment by ttung** [comment]
The same wheel shows up multiple times, in different subdirectories.  I assume that is because each library is saving its own dependent wheels.  This seems unnecessary, given we specify the entire set of libraries in requirements.txt.

**Comment by kislyuk** [comment]
Yes, this is not harmful in its current state, but could cause problems if different packages pull in different versions of dependencies in their graphs. I'll see if I can take just the one wheel for each package itself and throw away the rest.

**Comment by kislyuk** [comment]
(in other words the dependencies pulled in through subgraphs here actually don't respect the pins set in requirements.txt)

**Comment by kislyuk** [comment]
In https://github.com/HumanCellAtlas/data-store/pull/387.

**Pull request merged**
