### PR TITLE
Remove magic constants from checkout code.

### PR DESCRIPTION
**Pull request by ttung**
Also renamed some variables named `bundle_id` or `bundle_fqid` that were actually bundle_uuid.  Also renamed some variables named `version` that were actually bundle_version.

Test plan: Deployed daemon and ran integration+standalone checkout tests.

### CODE REVIEW

**Comment by ttung** [comment]
Did you mean Enum?

**Comment by mweiden** [comment]
@ttung no I meant a class or struct that you could load with the fields in the event and exposed as properties. Might be easier than lots of dict keys. This is a total nit, though

**Comment by ttung** [comment]
Can one json-serialize a namedtuple?

**Comment by ttung** [comment]
answer: nope.

**Comment by ttung** [comment]
python's json library really needs to a way for types to provide serialization and deserialization methods. :(

**Pull request merged**
