### PR TITLE
Make Elasticsearch indexes replica specific

### PR DESCRIPTION
**Pull request by mikebaumann**
Change Elasticsearch index names to be replica specific to enable replica
independent indexing, search, subscription/notification.
This commit is focused on replica specific indexing, with changes
to search and subscription for all tests to pass with replica specific indexes.
Additional changes are required to make the search route replica aware,
and additional GCP-specific testing is required for subscriptions,
which will be done as additional PRs.

### CODE REVIEW

**Comment by mikebaumann** [comment]
I welcome suggestions for making it cleaner/simpler, yet please keep in mind there are two indexes that need to be made replica specific, the one for the index docs and the one for the subscriptions.

**Comment by kislyuk** [comment]
Refactoring it now.

**Comment by kislyuk** [comment]
My refactor is in https://github.com/HumanCellAtlas/data-store/pull/405 vs. this branch.

**Comment by ttung** [comment]
I thought we discussed standing up a separate instance for each replica.  I can't envision any scenario where it makes sense to make one instance serve multiple replicas.

**Comment by kislyuk** [comment]
I think I'd prefer to have all replica specific indexes reside in the same ES cluster. This makes it easier to manage ES connections.

**Comment by ttung** [comment]
When would we reuse connections for ES?

**Comment by kislyuk** [comment]
ES queries will go to replica-specific indexes. A lambda may service many requests over its lifetime, each directed to a particular replica. Communicating with multiple ES instances requires setting up and caching a connection for each of them. I would rather have one ES instance serving the entire stage, until we go to replica-specific API service deployments embedded in their replicas' clouds (i.e. deploy the DSS API services on GCP).

**Comment by ttung** [comment]
What's the cost of caching multiple connections?

**Comment by kislyuk** [comment]
IMHO the main cost is code complexity.

**Comment by ttung** [comment]
I don't think the code would be that more complicated, and splitting it in the future is much more complicated than doing it now.

However, I'll defer to you guys on this.  Maybe you can ask the ES contractor. :)

**Comment by ttung** [comment]
Let's put it this way: would you put all the data for different deployments on the same S3 bucket?

Also, you have to have code to namespace the indices.  That is no different than code to namespace the instances.

**Comment by Bento007** [comment]
Closed by mistake

**Pull request merged**
